### ISSUE TITLE
Values on "write data" 

### ISSUE THREAD

**Issue by davidjgmarques** [fiorotto8/HVGEM_MANGO#2]
The values written with the button "Write data" that are afterward read by the MIDAS DAQ should refer to the input value and not the real value.
This because the real value fluctuates within a couple of volts which then might complicate the analysis directly from the SQL Logbook. For instance, If I want to select the runs with a given voltage with a filter, problems might arise when the *real* voltage is slightly different from the *expected* one. For this reason, I believe it is better to record the *expected* value instead of the real one.

**Comment by fiorotto8** [comment]
Now, the code writes only the VSETs. The output file is now different. I am also changing the DAQ part that reads the values from the shared folder

**Comment by davidjgmarques** [comment]
Grande!Enviado do meu iPhoneEm 12 de dez. de 2023, à(s) 12:01, Davide Fiorina ***@***.***> escreveu:﻿
Closed #2 as completed.
